### ISSUE TITLE
WorkflowScript: 2: unable to resolve class Library ,  unable to find class for annotation

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/pipeline-test-project#54]
![image](https://cloud.githubusercontent.com/assets/11987492/20996553/686f2c72-bd39-11e6-90c1-56c2a337638c.png)

**Comment by rawlingsj** [comment]
The `@Library` annotation only works with the recent Jenkins2 updated dependencies.  

More details in this post https://groups.google.com/forum/#!topic/fabric8/vKAjfwCTG1A

FWIW this is a test project used by fabric8's own release pipelines.  It's not expected to do anything other than validate the fabric8 release infra and pipeline scripts.
